apiVersion: apps/v1
kind: Deployment
metadata:
  name: alos-cogger-deployment
  labels:
    app: alos-cogger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alos-cogger-deployment
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: deafrica-ec2-s3_access
      labels:
        app: alos-cogger-deployment
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - spot
      containers:
      - name: alos-cog-files
        image: opendatacube/alos-cogger
        command: [ "python3", "run_job.py" ]
        resources:
          requests:
            cpu: 1.0
            memory: 8192Mi
          limits:
            cpu: 1
            memory: 8192Mi
        tty: true
        stdin: true
        env:
        - name: AWS_DEFAULT_REGION
          value: "us-west-2"
        - name: S3_BUCKET
          value: "test-results-deafrica-staging-west"
        - name: S3_PATH
          value: "alos"
        - name: SQS_QUEUE
          value: "alex-alive-queue"


      