apiVersion: apps/v1
kind: Deployment
metadata:
  name: alos-cogger-deployment
  namespace: processing
  labels:
    app: alos-cogger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alos-cogger-deployment
  template:
    metadata:
      labels:
        app: alos-cogger-deployment
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - spot
      containers:
      - name: alos-cogger
        image: opendatacube/alos-cogger
        command: [ "python3", "run_job.py" ]
        resources:
          requests:
            cpu: 1.0
            memory: 8192Mi
          limits:
            cpu: 2.0
            memory: 16384Mi
        tty: true
        stdin: true
        env:
        - name: AWS_DEFAULT_REGION
          value: "us-west-2"
        - name: S3_BUCKET
          value: "deafrica-data-dev"
        - name: S3_PATH
          value: "jaxa/alos_palsar_mosaic"
        - name: SQS_QUEUE
          value: "alex-alive-queue"
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: processing-aws-creds-prod
              key: AWS_DEFAULT_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: processing-aws-creds-prod
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: processing-aws-creds-prod
              key: AWS_SECRET_ACCESS_KEY
