apiVersion: v1
kind: Pod
metadata:
  name: alos-cog-files
  labels:
    app: alos-cog-files
  annotations:
    iam.amazonaws.com/role: deafrica-ec2-s3_access
spec:
  nodeSelector:
    beta.kubernetes.io/os: spot
  restartPolicy: Never
  containers:
  - name: alos-cog-files
    image: opendatacube/alos-cogger
    args: [ "python3", "run_job.py" ]
    resources:
      requests:
        cpu: 1
        memory: 8192Mi
      limits:
        memory: 8192Mi
    tty: true
    stdin: true
    env:
    - name: S3_BUCKET
      value: "deafrica-data-dev"
    - name: S3_PATH
      value: "alos"
    - name: SQS_QUEUE
      value: "alex-alive-queue"
    - name: AWS_DEFAULT_REGION
      valueFrom:
        secretKeyRef:
          name: processing-aws-creds-prod
          key: AWS_DEFAULT_REGION
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: processing-aws-creds-prod
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: processing-aws-creds-prod
          key: AWS_SECRET_ACCESS_KEY
